from typing import Any
from datetime import datetime, timedelta
from models import ApplicationInput
from utils import build_inquiry_id
from logic import build_website_payload, map_website_json_to_internal_model
from state import append_log
from actions import (
    run_scoring, send_to_teamlead, team_approve, run_rate_calculation,
    generate_offer, send_signature, customer_sign, send_mail
)

def create_seed_applications() -> list[dict[str, Any]]:
    base_time = datetime(2026, 3, 25, 8, 15, 0)
    seed_definitions = [
        {
            "firstName": "Erika",
            "lastName": "Sommer",
            "email": "erika.sommer@mflb-demo.de",
            "address": "Rosenweg 3",
            "postalCode": "80331",
            "city": "München",
            "employer": "Lumen Handels GmbH",
            "employerVatId": "DE214567890",
            "monthlyNetIncome": 3400,
            "employedSince": "2019-04-01",
            "iban": "DE10500105170648489890",
            "loanType": "Konsumentenkredit",
            "loanAmount": 12000,
            "termMonths": 48,
            "purpose": "Einrichtung Wohnung",
            "pipeline": ["score", "teamlead"],
        },
        {
            "firstName": "Leon",
            "lastName": "Meier",
            "email": "leon.meier@mflb-demo.de",
            "address": "Marktstraße 12",
            "postalCode": "20095",
            "city": "Hamburg",
            "employer": "Dockline AG",
            "employerVatId": "DE198765432",
            "monthlyNetIncome": 4100,
            "employedSince": "2017-09-01",
            "iban": "DE74500105175407324931",
            "loanType": "Konsumentenkredit",
            "loanAmount": 8500,
            "termMonths": 36,
            "purpose": "Fahrzeugkauf",
            "pipeline": ["score", "rate", "generate", "signature"],
        },
        {
            "firstName": "Sarah",
            "lastName": "Beck",
            "email": "sarah.beck@mflb-demo.de",
            "address": "Alte Gasse 8",
            "postalCode": "70173",
            "city": "Stuttgart",
            "employer": "Beck Design Studio",
            "employerVatId": "DE345672198",
            "monthlyNetIncome": 2850,
            "employedSince": "2022-02-01",
            "iban": "DE08500105179858451595",
            "loanType": "Konsumentenkredit",
            "loanAmount": 6500,
            "termMonths": 24,
            "purpose": "Küchenmodernisierung",
            "pipeline": [],
        },
        {
            "firstName": "David",
            "lastName": "Krüger",
            "email": "david.krueger@mflb-demo.de",
            "address": "Parkallee 91",
            "postalCode": "28195",
            "city": "Bremen",
            "employer": "Krüger Eventtechnik",
            "employerVatId": "DE987654321",
            "monthlyNetIncome": 4700,
            "employedSince": "2016-01-01",
            "iban": "DE98500105172429448490",
            "loanType": "Konsumentenkredit",
            "loanAmount": 30000,
            "termMonths": 72,
            "purpose": "Freie Verwendung",
            "pipeline": [],
        },
        {
            "firstName": "Miriam",
            "lastName": "Yilmaz",
            "email": "miriam.yilmaz@mflb-demo.de",
            "address": "Schillerplatz 22",
            "postalCode": "50667",
            "city": "Köln",
            "employer": "Urban Habitat GmbH",
            "employerVatId": "DE147258369",
            "monthlyNetIncome": 5600,
            "employedSince": "2015-03-01",
            "iban": "DE69500105173648295054",
            "loanType": "Baufinanzierung",
            "loanAmount": 180000,
            "termMonths": 240,
            "purpose": "Eigentumswohnung",
            "pipeline": [],
        },
        {
            "firstName": "Robert",
            "lastName": "Engel",
            "email": "robert.engel@mflb-demo.de",
            "address": "Industrieweg 44",
            "postalCode": "60311",
            "city": "Frankfurt am Main",
            "employer": "Engel Maschinenbau SE",
            "employerVatId": "DE111222333",
            "monthlyNetIncome": 7200,
            "employedSince": "2012-11-01",
            "iban": "DE97500105170648489810",
            "loanType": "Großkredit",
            "loanAmount": 250000,
            "termMonths": 84,
            "purpose": "Expansion Betrieb",
            "pipeline": [],
        },
        {
            "firstName": "Lisa",
            "lastName": "Hoffmann",
            "email": "lisa.hoffmann@mflb-demo.de",
            "address": "Auenweg 27",
            "postalCode": "01067",
            "city": "Dresden",
            "employer": "Hoffmann Consulting",
            "employerVatId": "DE444555666",
            "monthlyNetIncome": 3900,
            "employedSince": "2018-06-01",
            "iban": "DE17500105173648295014",
            "loanType": "Konsumentenkredit",
            "loanAmount": 19800,
            "termMonths": 72,
            "purpose": "Modernisierung Wohnung",
            "pipeline": ["score", "teamlead", "approve", "rate", "generate"],
        },
        {
            "firstName": "Jonas",
            "lastName": "Adler",
            "email": "jonas.adler@mflb-demo.de",
            "address": "Bachstraße 17",
            "postalCode": "90402",
            "city": "Nürnberg",
            "employer": "Adler Systems GmbH",
            "employerVatId": "DE333444555",
            "monthlyNetIncome": 3600,
            "employedSince": "2020-07-01",
            "iban": "DE51500105170648555370",
            "loanType": "Konsumentenkredit",
            "loanAmount": 7200,
            "termMonths": 48,
            "purpose": "Umschuldung",
            "pipeline": ["score", "rate", "generate", "signature", "customer-sign", "mail"],
        },
        {
            "firstName": "Cem",
            "lastName": "Arslan",
            "email": "cem.arslan@mflb-demo.de",
            "address": "Turmring 9",
            "postalCode": "68159",
            "city": "Mannheim",
            "employer": "LogiChain Europe",
            "employerVatId": "DE777888999",
            "monthlyNetIncome": 3000,
            "employedSince": "2023-01-01",
            "iban": "DE28500105170000202051",
            "loanType": "Konsumentenkredit",
            "loanAmount": 10400,
            "termMonths": 48,
            "purpose": "Elektronik",
            "pipeline": ["score", "teamlead"],
        },
        {
            "firstName": "Pia",
            "lastName": "Weber",
            "email": "pia.weber@mflb-demo.de",
            "address": "Bahnhofstraße 6",
            "postalCode": "04109",
            "city": "Leipzig",
            "employer": "Weber Media OHG",
            "employerVatId": "DE666777888",
            "monthlyNetIncome": 3250,
            "employedSince": "2021-10-01",
            "iban": "DE75500105170648489850",
            "loanType": "Konsumentenkredit",
            "loanAmount": 9400,
            "termMonths": 36,
            "purpose": "Freie Verwendung",
            "pipeline": ["score", "rate"],
        },
        {
            "firstName": "Nora",
            "lastName": "Klein",
            "email": "nora.klein@mflb-demo.de",
            "address": "Rathausgasse 5",
            "postalCode": "89073",
            "city": "Ulm",
            "employer": "Klein Concept Store",
            "employerVatId": "DE812345670",
            "monthlyNetIncome": 2800,
            "employedSince": "2022-06-01",
            "iban": "DE91500105170648489910",
            "loanType": "Konsumentenkredit",
            "loanAmount": 5400,
            "termMonths": 24,
            "purpose": "Möbelkauf",
            "pipeline": [],
        },
        {
            "firstName": "Tim",
            "lastName": "Richter",
            "email": "tim.richter@mflb-demo.de",
            "address": "Mühlenweg 18",
            "postalCode": "44135",
            "city": "Dortmund",
            "employer": "Richter Elektrotechnik",
            "employerVatId": "DE923456781",
            "monthlyNetIncome": 3500,
            "employedSince": "2019-08-01",
            "iban": "DE22500105170648489920",
            "loanType": "Konsumentenkredit",
            "loanAmount": 15000,
            "termMonths": 60,
            "purpose": "Renovierung",
            "pipeline": ["score", "teamlead"],
        },
        {
            "firstName": "Aylin",
            "lastName": "Demir",
            "email": "aylin.demir@mflb-demo.de",
            "address": "Gartenstraße 28",
            "postalCode": "30159",
            "city": "Hannover",
            "employer": "Demir Services GmbH",
            "employerVatId": "DE834567892",
            "monthlyNetIncome": 3300,
            "employedSince": "2021-01-01",
            "iban": "DE33500105170648489930",
            "loanType": "Konsumentenkredit",
            "loanAmount": 9900,
            "termMonths": 48,
            "purpose": "Umschuldung",
            "pipeline": ["score", "rate"],
        },
        {
            "firstName": "Marcel",
            "lastName": "Vogt",
            "email": "marcel.vogt@mflb-demo.de",
            "address": "Bergstraße 44",
            "postalCode": "53111",
            "city": "Bonn",
            "employer": "Vogt Logistik AG",
            "employerVatId": "DE845678903",
            "monthlyNetIncome": 4300,
            "employedSince": "2016-04-01",
            "iban": "DE44500105170648489940",
            "loanType": "Konsumentenkredit",
            "loanAmount": 18500,
            "termMonths": 72,
            "purpose": "Sanierung Hausrat",
            "pipeline": ["score", "teamlead", "approve", "rate", "generate"],
        },
        {
            "firstName": "Helena",
            "lastName": "Fuchs",
            "email": "helena.fuchs@mflb-demo.de",
            "address": "Marktplatz 9",
            "postalCode": "39104",
            "city": "Magdeburg",
            "employer": "Fuchs Interior GmbH",
            "employerVatId": "DE856789014",
            "monthlyNetIncome": 3900,
            "employedSince": "2018-11-01",
            "iban": "DE55500105170648489950",
            "loanType": "Konsumentenkredit",
            "loanAmount": 11200,
            "termMonths": 48,
            "purpose": "Freie Verwendung",
            "pipeline": ["score", "teamlead", "approve"],
        },
        {
            "firstName": "Paul",
            "lastName": "Steiner",
            "email": "paul.steiner@mflb-demo.de",
            "address": "Lindenring 16",
            "postalCode": "54290",
            "city": "Trier",
            "employer": "Steiner IT Solutions",
            "employerVatId": "DE867890125",
            "monthlyNetIncome": 4100,
            "employedSince": "2017-02-01",
            "iban": "DE66500105170648489960",
            "loanType": "Konsumentenkredit",
            "loanAmount": 7800,
            "termMonths": 36,
            "purpose": "Elektronik",
            "pipeline": ["score", "rate", "generate", "signature", "customer-sign", "mail"],
        },
        {
            "firstName": "Farah",
            "lastName": "Özdemir",
            "email": "farah.oezdemir@mflb-demo.de",
            "address": "Kanalweg 2",
            "postalCode": "28199",
            "city": "Bremen",
            "employer": "Özdemir Immobilien",
            "employerVatId": "DE878901236",
            "monthlyNetIncome": 6800,
            "employedSince": "2014-09-01",
            "iban": "DE77500105170648489970",
            "loanType": "Baufinanzierung",
            "loanAmount": 240000,
            "termMonths": 300,
            "purpose": "Neubau",
            "pipeline": [],
        },
        {
            "firstName": "Martin",
            "lastName": "Schade",
            "email": "martin.schade@mflb-demo.de",
            "address": "Gewerbepark 11",
            "postalCode": "97070",
            "city": "Würzburg",
            "employer": "Schade Produktions GmbH",
            "employerVatId": "DE889012347",
            "monthlyNetIncome": 7600,
            "employedSince": "2013-05-01",
            "iban": "DE88500105170648489980",
            "loanType": "Großkredit",
            "loanAmount": 130000,
            "termMonths": 96,
            "purpose": "Maschinenpark",
            "pipeline": [],
        },
        {
            "firstName": "Clara",
            "lastName": "Neumann",
            "email": "clara.neumann@mflb-demo.de",
            "address": "Sonnenweg 31",
            "postalCode": "18055",
            "city": "Rostock",
            "employer": "Neumann Healthcare",
            "employerVatId": "DE890123458",
            "monthlyNetIncome": 4400,
            "employedSince": "2019-01-01",
            "iban": "DE99500105170648489990",
            "loanType": "Konsumentenkredit",
            "loanAmount": 22000,
            "termMonths": 60,
            "purpose": "Freie Verwendung",
            "pipeline": [],
        },
        {
            "firstName": "Deniz",
            "lastName": "Kara",
            "email": "deniz.kara@mflb-demo.de",
            "address": "Fliederweg 14",
            "postalCode": "34117",
            "city": "Kassel",
            "employer": "Kara Media House",
            "employerVatId": "DE901234569",
            "monthlyNetIncome": 3100,
            "employedSince": "2022-09-01",
            "iban": "DE11500105170648489001",
            "loanType": "Konsumentenkredit",
            "loanAmount": 10100,
            "termMonths": 48,
            "purpose": "Fahrzeugkauf",
            "pipeline": ["score"],
        },
        {
            "firstName": "Jana",
            "lastName": "Lorenz",
            "email": "jana.lorenz@mflb-demo.de",
            "address": "Hafenweg 21",
            "postalCode": "10115",
            "city": "Berlin",
            "employer": "Lorenz Office Services",
            "employerVatId": "DE912340001",
            "monthlyNetIncome": 2950,
            "employedSince": "2021-05-01",
            "iban": "DE12500105170648489011",
            "loanType": "Konsumentenkredit",
            "loanAmount": 5800,
            "termMonths": 24,
            "purpose": "Möblierung",
            "pipeline": [],
        },
        {
            "firstName": "Felix",
            "lastName": "Brandt",
            "email": "felix.brandt@mflb-demo.de",
            "address": "Westend 13",
            "postalCode": "45127",
            "city": "Essen",
            "employer": "Brandt Facility Solutions",
            "employerVatId": "DE912340002",
            "monthlyNetIncome": 3450,
            "employedSince": "2018-02-01",
            "iban": "DE13500105170648489012",
            "loanType": "Konsumentenkredit",
            "loanAmount": 9900,
            "termMonths": 36,
            "purpose": "Fahrzeugreparatur",
            "pipeline": ["score", "rate"],
        },
        {
            "firstName": "Sophie",
            "lastName": "Albrecht",
            "email": "sophie.albrecht@mflb-demo.de",
            "address": "Lechufer 7",
            "postalCode": "86150",
            "city": "Augsburg",
            "employer": "Albrecht Medien GmbH",
            "employerVatId": "DE912340003",
            "monthlyNetIncome": 3800,
            "employedSince": "2017-11-01",
            "iban": "DE14500105170648489013",
            "loanType": "Konsumentenkredit",
            "loanAmount": 12500,
            "termMonths": 60,
            "purpose": "Badsanierung",
            "pipeline": ["score", "teamlead"],
        },
        {
            "firstName": "Lukas",
            "lastName": "Werner",
            "email": "lukas.werner@mflb-demo.de",
            "address": "Fördeblick 4",
            "postalCode": "24103",
            "city": "Kiel",
            "employer": "Werner Maritim GmbH",
            "employerVatId": "DE912340004",
            "monthlyNetIncome": 4200,
            "employedSince": "2016-09-01",
            "iban": "DE15500105170648489014",
            "loanType": "Konsumentenkredit",
            "loanAmount": 17800,
            "termMonths": 72,
            "purpose": "Umschuldung",
            "pipeline": ["score", "teamlead", "approve", "rate", "generate"],
        },
        {
            "firstName": "Yasmin",
            "lastName": "Celik",
            "email": "yasmin.celik@mflb-demo.de",
            "address": "Rheinbogen 12",
            "postalCode": "40213",
            "city": "Düsseldorf",
            "employer": "Celik Retail Solutions",
            "employerVatId": "DE912340005",
            "monthlyNetIncome": 3550,
            "employedSince": "2020-03-01",
            "iban": "DE16500105170648489015",
            "loanType": "Konsumentenkredit",
            "loanAmount": 8400,
            "termMonths": 48,
            "purpose": "Hausrat",
            "pipeline": ["score", "rate", "generate", "signature", "customer-sign", "mail"],
        },
        {
            "firstName": "Hannes",
            "lastName": "Berger",
            "email": "hannes.berger@mflb-demo.de",
            "address": "Schlossberg 19",
            "postalCode": "79098",
            "city": "Freiburg",
            "employer": "Berger Planungsgesellschaft",
            "employerVatId": "DE912340006",
            "monthlyNetIncome": 4050,
            "employedSince": "2015-10-01",
            "iban": "DE17500105170648489016",
            "loanType": "Konsumentenkredit",
            "loanAmount": 19900,
            "termMonths": 84,
            "purpose": "Modernisierung",
            "pipeline": ["score", "teamlead"],
        },
        {
            "firstName": "Bianca",
            "lastName": "Roth",
            "email": "bianca.roth@mflb-demo.de",
            "address": "Südwall 3",
            "postalCode": "04103",
            "city": "Leipzig",
            "employer": "Roth Industrieholding",
            "employerVatId": "DE912340007",
            "monthlyNetIncome": 8900,
            "employedSince": "2011-01-01",
            "iban": "DE18500105170648489017",
            "loanType": "Großkredit",
            "loanAmount": 320000,
            "termMonths": 96,
            "purpose": "Expansion Filiale",
            "pipeline": [],
        },
        {
            "firstName": "Ole",
            "lastName": "Hartmann",
            "email": "ole.hartmann@mflb-demo.de",
            "address": "Havelpark 8",
            "postalCode": "14467",
            "city": "Potsdam",
            "employer": "Hartmann Architektur PartG",
            "employerVatId": "DE912340008",
            "monthlyNetIncome": 7600,
            "employedSince": "2014-07-01",
            "iban": "DE19500105170648489018",
            "loanType": "Baufinanzierung",
            "loanAmount": 280000,
            "termMonths": 300,
            "purpose": "Neubau Einfamilienhaus",
            "pipeline": [],
        },
        {
            "firstName": "Greta",
            "lastName": "König",
            "email": "greta.koenig@mflb-demo.de",
            "address": "Seeblick 27",
            "postalCode": "18055",
            "city": "Rostock",
            "employer": "König Eventservice",
            "employerVatId": "DE912340009",
            "monthlyNetIncome": 3700,
            "employedSince": "2019-12-01",
            "iban": "DE20500105170648489019",
            "loanType": "Konsumentenkredit",
            "loanAmount": 22000,
            "termMonths": 84,
            "purpose": "Freie Verwendung",
            "pipeline": [],
        },
        {
            "firstName": "Sami",
            "lastName": "Rahman",
            "email": "sami.rahman@mflb-demo.de",
            "address": "Europaallee 15",
            "postalCode": "66111",
            "city": "Saarbrücken",
            "employer": "Rahman IT Services",
            "employerVatId": "DE912340010",
            "monthlyNetIncome": 3150,
            "employedSince": "2022-04-01",
            "iban": "DE21500105170648489020",
            "loanType": "Konsumentenkredit",
            "loanAmount": 10100,
            "termMonths": 48,
            "purpose": "Weiterbildung",
            "pipeline": ["score", "teamlead", "approve", "rate"],
        },
        {
            "firstName": "Carina",
            "lastName": "Wolf",
            "email": "carina.wolf@mflb-demo.de",
            "address": "Messeplatz 6",
            "postalCode": "50670",
            "city": "Köln",
            "employer": "Wolf Projektservice",
            "employerVatId": "DE912340011",
            "monthlyNetIncome": 3275,
            "employedSince": "2020-08-01",
            "iban": "DE22500105170648489021",
            "loanType": "Konsumentenkredit",
            "loanAmount": 7600,
            "termMonths": 36,
            "purpose": "Haushaltsgeräte",
            "pipeline": ["score-error"],
        },
        {
            "firstName": "Mehmet",
            "lastName": "Acar",
            "email": "mehmet.acar@mflb-demo.de",
            "address": "Nordring 42",
            "postalCode": "48143",
            "city": "Münster",
            "employer": "Acar Mobility Services",
            "employerVatId": "DE912340012",
            "monthlyNetIncome": 3480,
            "employedSince": "2018-05-01",
            "iban": "DE23500105170648489022",
            "loanType": "Konsumentenkredit",
            "loanAmount": 6900,
            "termMonths": 30,
            "purpose": "Motorradkauf",
            "pipeline": ["score", "rate", "generate"],
        },
    ]

    applications: list[dict[str, Any]] = []

    for index, definition in enumerate(seed_definitions, start=1):
        created_at = (base_time + timedelta(minutes=index * 19)).replace(microsecond=0).isoformat()
        inquiry_id = build_inquiry_id(index, created_at)
        application_input = ApplicationInput(
            **{key: value for key, value in definition.items() if key != "pipeline"}
        )
        payload = build_website_payload(application_input, created_at, inquiry_id)
        record = map_website_json_to_internal_model(
            payload,
            f"seed-{index}",
            inquiry_id,
            created_at,
            application_input.model_dump(),
        )
        append_log(record, "Website", "Seed-Fall wurde als JSON aus dem Online-Kanal übernommen.")

        for step in definition["pipeline"]:
            if step == "score":
                run_scoring(record)
            elif step == "score-error":
                run_scoring(record, force_error=True)
            elif step == "teamlead":
                send_to_teamlead(record)
            elif step == "approve":
                team_approve(record)
            elif step == "rate":
                run_rate_calculation(record)
            elif step == "generate":
                generate_offer(record)
            elif step == "signature":
                send_signature(record)
            elif step == "customer-sign":
                customer_sign(record)
            elif step == "mail":
                send_mail(record)

        applications.append(record)

    applications.sort(key=lambda item: item["createdAt"], reverse=True)
    return applications
